### ISSUE TITLE
Внимание! для CSS-костыля `.selectorName.selectorName` нужно учитывать дублирующийся селектор

### ISSUE THREAD

**Issue by taksenov** [taksenov/dead-code-finder#6]
```scss
.fullScreenModal.fullScreenModal {
  display: flex !important;
  flex-direction: column !important;
  height: 100% !important;
  top: 0 !important;
  width: 100% !important;
  left: 0 !important;
  margin: 0em auto !important;
}
```

выведет AST:

```json
    {
      "type": "rule",
      "selector": ".fullScreenModal.fullScreenModal"
   }
```
